### ISSUE TITLE
reconstructionMode in  ismrmrd/schema/ismrmrd.xsd 

### ISSUE THREAD

**Issue by marcsous** [ismrmrd/ismrmrd#146]
Can we add a new element in encoding to store the reconstructionMode? It's a flag that specifies what type of image to produce. On Siemens it's a long value: 1=magnitude 2=phase 4=real part 8=magn+phase etc. GE does something similar with a bitmask. I'm pretty sure this type of flag is universal to all vendors but parsing it can be left to the vendor specific xml/xsl parameter maps.

```
  <xs:complexType name="encoding">
    <xs:all>
      <xs:element maxOccurs="1" minOccurs="1" name="encodedSpace" type="encodingSpaceType"/>
      <xs:element maxOccurs="1" minOccurs="1" name="reconSpace" type="encodingSpaceType"/>
      <xs:element maxOccurs="1" minOccurs="1" name="encodingLimits" type="encodingLimitsType"/>
      <xs:element maxOccurs="1" minOccurs="1" name="trajectory" type="trajectoryType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="trajectoryDescription" type="trajectoryDescriptionType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="parallelImaging" type="parallelImagingType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="echoTrainLength" type="xs:long"/>
      <xs:element maxOccurs="1" minOccurs="0" name="reconstructionMode" type="xs:long"/>
    </xs:all>
  </xs:complexType>
```

**Comment by dchansen** [comment]
Bitmasks, longs, etc do not really make a lot of sense in the XML. It just makes things hard to read for humans. If we implement something like this it should be a list of some enumerated type:
`
<xs:element name="reconstructionMode">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="magnitude"/>
      <xs:enumeration value="phase"/>
      <xs:enumeration value="Scalar"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> `

and then 
`<xs:element maxOccurs="3" minOccurs="0" name="reconstructionModes" type="reconstructionMode"/>`

That being said, shouldn't this be decided by the reconstruction, rather than the data? 
@xueh2 @ACampbellWashburn Could you comment?

**Comment by marcsous** [comment]
Thanks - that makes a lot of sense. The following types are available in Siemens - magnitude, phase, real part, magnitude+phase and psir (phase sensitive inversion recovery). Maybe something like this?
```
                 <userParameterString>
                    <name>reconstructionMode</name>
                    <value>
                    <xsl:choose>
                        <xsl:when test="siemens/MEAS/ucReconstructionMode = 1">magnitude</xsl:when>
                        <xsl:when test="siemens/MEAS/ucReconstructionMode = 2">phase</xsl:when>
                        <xsl:when test="siemens/MEAS/ucReconstructionMode = 4">real_part</xsl:when>
                        <xsl:when test="siemens/MEAS/ucReconstructionMode = 8">magn_phase</xsl:when>
                        <xsl:when test="siemens/MEAS/ucReconstructionMode =16">real_phase</xsl:when>
                        <xsl:when test="siemens/MEAS/ucReconstructionMode =32">psir</xsl:when>
			<xsl:otherwise>other</xsl:otherwise>
		    </xsl:choose>
		    </value>
                 </userParameterString>
```

**Comment by hansenms** [comment]
I don’t think the raw data format should be overly focused on what images to recon from a given dataset. Whether you reconstruct magnitude or phase images or both or some other kind of image is reconstruction dependent and not data dependent. 

I’m closing this for now since it’s been inactive for a while. Happy to discuss more, but we would need some deeper discussion on whether this should be done at all and if so how.
