### ISSUE TITLE
Image format - Keep our own or go with a "standard"

### ISSUE THREAD

**Issue by hansenms** [ismrmrd/ismrmrd#58]
In the current version of ISMRMRD (1.x) we have an image format. The question is if we should continue to have that or we should adopt some existing format. Some of the choices are:
1. nifti
2. Analyze
3. MINC
4. DICOM

Please add others. 

They all have issues. They all have advantages. 

The ISMRMRD format has the advantage of allowing images to be stored as complex images. However, due to the lack of native support for complex arrays, it is actually not well supported or easy to display. We also have a meta data structure that we pass along with the images, but such a meta data structure could be maintained with other formats too. 

The advantages of picking a "standard" format for images is that it is, well standard and we could simply stop supporting the image format based on the reasoning that ISMRMRD is really about storing raw data.

I would like to invite comments on this. It is important since we are moving ahead with the next version of the format. 

@xueh2 @hjmjohnson @naegelejd @inati  @ACampbellWashburn @dchansen @DANAJK @KrisThielemans @mklassen @kvahed @ojosephs @welcheb @srapacchi @pvelasco @CCPPETMR 
@vadre

Please comment. This is an important decision.

**Comment by srapacchi** [comment]
Hi Michael,
 that is a very good point. In our institution, we use the image format a lot as we promoted the implementation of pipelines with generic reconstruction + matlab image gadget for prototyping processing online. Considering the use we have, I would prefer DICOM format over Nifti and Analyze. The later losing a lot of metadata. (and I do not know MINC)
However, maintaining complex data appears necessary for many applications. Is there another solution than splitting real/imaginary data if the format were to be changed ?

Stan

**Comment by DANAJK** [comment]
Hi,

In clinical research, DICOM is the only universally accepted standard, there are excellent viewers and it is the format of data that comes off the scanner – against which you might be making comparisons with your own reconstruction. For end-users, writing DICOM is difficult so having it done as part of ISMRMRD processing would be useful.

On the other hand, if the DICOM is embedded within an hdf5 file, you will not be able to just open the hdf5 file using OsiriX or MATLAB’s dicomread. You would need to write out a temporary file and to do that we would need to supply software that takes care of transfer syntax (endian-ness etc), DICOM UIDs, series numbers etc.

ISMRMRD facilitates comparison of algorithms and one of its strengths is the availability of raw to ISMRMRD convertors. Users may wish to compare, say Gadgetron and BART functionality, so a simple data format makes this a lot easier. Also, DICOM-MR uses 16bit integers which loose precision and need re-scaling. Furthermore, if developers using ISMRMRD were forced to use DICOM format, I fear the bar to development would be too high.

My suggestion is that up until final output, images (and I think you mean both images and processed k-space here?) are stored in a simple format that is very clearly documented with example read/write scripts provided. We then need to make it as painless as possible to create DICOMs/Niftis for clinical comparison, probably best done by providing a separate ISMRMRD to DICOM/Nifti convertor.

These were just my initial thoughts.

David A.

**Comment by hjmjohnson** [comment]
I agree with David Atkinson’s comments.  

 

I would like to add that we should *NOT* use the *hdr/*img file extensions (aka Analyze).  One of the primary reasons for the existence of Nifit is that there are many inconsistent conventions used by different toolkits (Analyze^{TM}, SPM, FSL, AFNI all had different variants of the analyze format).  Those tools have all moved away from using Analyze and for the most part converged on using NiFTI.

 

I am partial to the NIFTI format for simple data, fixed information.  

 

I also think you should consider the Nearly Raw Raster Data NRRD file format.  It is well documented, extensible, flexible, and meets many of the needs for this community.

 

 

 

Regards,

Hans

--

**Comment by ojosephs** [comment]
Hi,

This ideas from Guillaume Flandin, at the FIL.
John Ashburner was in favour of DICOM - I'll pass on any further comments.

Oliver


Hi Oliver,

I just wanted to point this to you:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/bids-discussion
(mailing list for BIDS - http://www.nature.com/articles/sdata201644 )

It's only tangentially related to your question but if you look in the
thread "Proposed Change: Top-level folder to contain raw data", there is
a discussion about how to store raw data and ISMRMRD is mentioned.

Also you'll see that in BIDS, NIfTI is used and extra metadata are
stored as sidecar JSON files.

Best,
Guillaume.

2016-07-13 12:21 GMT+01:00 Hans Johnson <notifications@github.com>:

**Comment by mklassen** [comment]
I tend to use and view ISMRMRD as data interchange format. I often store intermediate results, which are often complex images, and transfer them between reconstruction tools. I chose ISMRMRD because it is

1. It is light weight. HDF5 libraries already exist on many HPC systems because of their widespread use in other fields. DICOM libraries are not nearly as common.
2. You can store multiple related datasets (and their relationships) within the same file. Personally I prefer storing all related data in a single large file rather than many smaller files. This prevents loosing/missing files and many HPC filesystems are optimized for storing/accessing/transferring a few large files rather than many small files.
3. You can access the data even without using the ISMRMRD library interface.

Personally, I would rather not loose the image storage within an ISMRMRD file as it has become critical to many of my existing workflows. However, I could see utility in including an ISMRMRD to DICOM converter as an optional tool within the ISMRMRD project.

**Comment by pvelasco** [comment]
Hi All,

I think there is a little bit of confusion on what "image format" we are
talking about.  The ISMRMRD (1.x) defines an ISMRMRD_Image structure.
Then, there is also the image you get from the Gadgetron with the
MRIImageWriter, which is HDF5 (not sure if this only applies to data
reconstructed using gadgetron_ismrmrd_client, as opposed to images sent
back to the scanner).

Which "image format" are we talking about?

-Pablo


-----------------------------
Pablo Velasco, Ph.D.
Senior Research Scientist
Center for Brain Imaging
New York University
6 Washington Place, Room 156
New York, NY 10003
Lab: (212) 992-8748
Fax: (212) 995-4570
-----------------------------

**Comment by hansenms** [comment]
Thanks for weighing in everybody. 

Let me start from the end of the thread and address the question from @pvelasco. I don't actually think there is any confusion. The ISMRMRD format defined a C++ (and Matlab and Python) data structure, which represents and image or more specifically a header and some pixel data. When you use the `gadgetron_ismrmrd_client` the images returned from the Gadgetron are in this format and the client will write an HDF5 representation of the image in the file. This is completely equivalent to the Acquisitions, which also have in memory representations in different languages and environments and they can be written and read using HDF5 files. The ISMRMRD::Dataset is what makes this connection between in memory representation and on the disk representation. In any case, they are the same concept. 

So when I was talking about images I mean both representations and what I was considering was whether we should use some other standard for defining these representations so that they would be more compatible with other software tools. 

What I am hearing is this:

* ISMRMRD Image format:
   * Advantages:
        * Flexible (in terms of metadata)
        * Lightweight
        * Easy to read the images even without having ISMRMRD API installed because we use HDF5
        * A collection of images (even from multiple studies) can reside in the same file (even with the raw data)
    * Disadvantages:
        * Not a "standard"
        * And related point, lack of standard viewing tools.
* Analyze/Nifty:
    * Advantages:
        * A standard format
        * Existing tools for viewing and converting
    * Disadvantages:
        * Some inconsistencies in use of the "standard"
        * Lacks flexible metadata structures and would need a meta data sidecar of sorts
        * Uses individual files (actually two files per image) and would not make a lot of sense to store in HDF5.
* DICOM
    * Advantages:
        * Is *the* standard. 
        * Could immediately be pushed to PACS, etc. 
        * DICOM viewers are readily available on many platforms. 
    * Disadvantages:
        * Not lightweight
        * Required many fields to be filled in in order to have a well formed DICOM. Many of these fields (like patient names) should not be on the wire.
        * Images are generally in fixed precision (16-bit), which makes downstream evaluation of algorithms problematic at times. 


So it sounds like:

* There is a need for a simple, lightweight representation of the images while processing, on the wire, and in files. There is no specific advantage to making that nifti over our current standard. 
* We should have better tools for getting to other formats (such as DICOM). 

The latter point is actually application specific. For the Gadgetron we could have a way to save in DICOM format. For that to work well, the user should be able to put in a document with all the additional needed fields that would get tagged on to the images when they return before they are written as DICOM. We could also have converter tools that perform similar functions. That would make it easier to push the results to PACS, etc. The client could even push directly to a PACS. There is some implementation work to get that done, but I think it could be very valuable, so I have opened an issue (https://github.com/gadgetron/gadgetron/issues/416) in the Gadgetron for that. 

My conclusion here is we should keep our own format. Let me know if I got it wrong.

**Comment by ghisvail** [comment]
My current lab uses Nifti extensively over DICOM. DICOM is considered the most generic format for data exchange, but its usage is not as easy as other conventional "header + raw data" format ala Nifti and ISMRMRD Image. Plus, there seems to be different "flavours" of DICOM amongst the neuro-imaging community and not all the so-called converters claim to support arbitrary DICOM files.

On the other hand, Nifti is just a conventional specification composed of a header format with "some" extensibility followed by raw data. I have not encountered much Nifti files saved as separate header and data files (which is what @hansenms refers to in the cons I guess). The ones we use here  are all saved as one single file, plus optional compression applied on top. FYI, there was also a recent update of the specification called Nifti-2, which takes advantage of 64-bit addressing, otherwise the format is similar to Nifti-1.

IMO, a better path forward would be to compare the ISMRMRD Image and Nifti specifications and verify whether essential fields are missing. If not, then Nifti should probably be adopted as the exchange format for images, so that support by third-party tools only requires decoding the HDF5 container of the ISMRMRD file before using their existing Nifti readers to deserialize.

**Comment by hansenms** [comment]
@ghisvail on the separate file issue. It is only marginally better to have one filer per image as opposed to two. If you have 1000 images coming out of a recon, it is still a bit problematic, right?

@ghisvail how do you deal with "metadata" in nifti in your lab? Specifically, one often needs to add tags (e.g. this is a T1 map) or some other application specific stuff. How easy is that to do in nifti? Where would be it stored. Somebody mentioned a JSON sidecar, is that how you do it?

@ghisvail if we store a nifti like image in an HDF5 file, and provide a reader to "decode" the HDF5 to actual nifti data structures, does it really matter if it is nifti as long as it can be converted on the fly to nifity, would that not achieve the same thing?

**Comment by ghisvail** [comment]
Sounds to me that we are mixing 2 different topics here:
1. Whether to keep using the ISMRMRD "archive" file, currently in HDF5 format.
2. Inside this archive, in which format to store images, currently as `ISMRMRD_Image`.

I should first clear out that I am not against 1) at all. It definitely fills a niche and is arguably a better option for exchanging a catalog of reconstructed images belonging to the same dataset, than multiple files, plus accompanying metadata written in a separate JSON file.

However, we should keep in mind that the reconstruction is not always the end of the processing pipeline, and further image analysis may benefit from having individual files (what @hansenms referred to as the *1000 images*) rather than one ISMRMRD archive. For instance in our lab, image analysis pipelines are performed on computing grids and usage of a single archive for parallel processing of the data is likely to bring a bandwidth penalty. As @hansenms mentioned, this could be easily solved by providing other tools to extract the images in the desired format from the ISMRMRD archive, but also by enabling Gadgetron to directly store the results directly in DICOM / Nifti files.

My doubts were mostly about 2), i.e. the need for a separate `ISMRMRD_Image` data structure over an existing standard such as `Nifti`. This thread did not show much evidence of the latter so far.

> Specifically, one often needs to add tags (e.g. this is a T1 map) or some other application specific stuff.

This could be allowed by the Nifti format as an [extension](http://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/extension.html). As to whether this specific field must be included in the data structure instead of as an extension, that is not something I can comment much about.

To be honest, for things like T1, T2, Dixon phase, b-values, I have seen those type of metadata more often embedded in the filename than with other means. Feel free to comment on how archaic and fragile this is, but this is just my personal observation over my time at King's and Imperial.

> how do you deal with "metadata" in nifti in your lab?

For small datasets, crafted filenames (often) or Nifti extensions (less often). For bigger datasets, we are currently investigating the usage of XNAT.

> if we store a nifti like image in an HDF5 file, and provide a reader to "decode" the HDF5 to actual nifti data structures, does it really matter if it is nifti as long as it can be converted on the fly to nifity, would that not achieve the same thing?

Sure, but I believe the path to least resistance for adoption by the research community would be to re-use existing standards. For the raw data, there were none that were available anyway, so `ISMRMRD_Acquisition` filled a gap. For `ISMRMRD_Image`, I am yet to be convinced by the advantages brought specifically by this format.

You have more mileage than I have here, so perhaps all I need is a bit more enlightenment to be convinced that this is not a potential case for [this](https://xkcd.com/927/). I took the freedom to copy both the Nifti and ISMRMRD_Image header specifications below if that can help.

Nifti-2
```
                         /***************************/ /**********************/ /************/
struct nifti_2_header {  /* NIFTI-2 usage           */ /* NIFTI-1 usage      */ /*  offset  */
                         /***************************/ /**********************/ /************/
   int   sizeof_hdr;     /*!< MUST be 540           */ /* int sizeof_hdr; (348) */   /*   0 */
   char  magic[8] ;      /*!< MUST be valid signature. */  /* char magic[4];    */   /*   4 */
   int16_t datatype;     /*!< Defines data type!    */ /* short datatype;       */   /*  12 */
   int16_t bitpix;       /*!< Number bits/voxel.    */ /* short bitpix;         */   /*  14 */
   int64_t dim[8];       /*!< Data array dimensions.*/ /* short dim[8];         */   /*  16 */
   double intent_p1 ;    /*!< 1st intent parameter. */ /* float intent_p1;      */   /*  80 */
   double intent_p2 ;    /*!< 2nd intent parameter. */ /* float intent_p2;      */   /*  88 */
   double intent_p3 ;    /*!< 3rd intent parameter. */ /* float intent_p3;      */   /*  96 */
   double pixdim[8];     /*!< Grid spacings.        */ /* float pixdim[8];      */   /* 104 */
   int64_t vox_offset;   /*!< Offset into .nii file */ /* float vox_offset;     */   /* 168 */
   double scl_slope ;    /*!< Data scaling: slope.  */ /* float scl_slope;      */   /* 176 */
   double scl_inter ;    /*!< Data scaling: offset. */ /* float scl_inter;      */   /* 184 */
   double cal_max;       /*!< Max display intensity */ /* float cal_max;        */   /* 192 */
   double cal_min;       /*!< Min display intensity */ /* float cal_min;        */   /* 200 */
   double slice_duration;/*!< Time for 1 slice.     */ /* float slice_duration; */   /* 208 */
   double toffset;       /*!< Time axis shift.      */ /* float toffset;        */   /* 216 */
   int64_t slice_start;  /*!< First slice index.    */ /* short slice_start;    */   /* 224 */
   int64_t slice_end;    /*!< Last slice index.     */ /* short slice_end;      */   /* 232 */
   char  descrip[80];    /*!< any text you like.    */ /* char descrip[80];     */   /* 240 */
   char  aux_file[24];   /*!< auxiliary filename.   */ /* char aux_file[24];    */   /* 320 */
   int qform_code ;      /*!< NIFTI_XFORM_* code.   */ /* short qform_code;     */   /* 344 */
   int sform_code ;      /*!< NIFTI_XFORM_* code.   */ /* short sform_code;     */   /* 348 */
   double quatern_b ;    /*!< Quaternion b param.   */ /* float quatern_b;      */   /* 352 */
   double quatern_c ;    /*!< Quaternion c param.   */ /* float quatern_c;      */   /* 360 */
   double quatern_d ;    /*!< Quaternion d param.   */ /* float quatern_d;      */   /* 368 */
   double qoffset_x ;    /*!< Quaternion x shift.   */ /* float qoffset_x;      */   /* 376 */
   double qoffset_y ;    /*!< Quaternion y shift.   */ /* float qoffset_y;      */   /* 384 */
   double qoffset_z ;    /*!< Quaternion z shift.   */ /* float qoffset_z;      */   /* 392 */
   double srow_x[4] ;    /*!< 1st row affine transform. */  /* float srow_x[4]; */   /* 400 */
   double srow_y[4] ;    /*!< 2nd row affine transform. */  /* float srow_y[4]; */   /* 432 */
   double srow_z[4] ;    /*!< 3rd row affine transform. */  /* float srow_z[4]; */   /* 464 */
   int slice_code ;      /*!< Slice timing order.   */ /* char slice_code;      */   /* 496 */
   int xyzt_units ;      /*!< Units of pixdim[1..4] */ /* char xyzt_units;      */   /* 500 */
   int intent_code ;     /*!< NIFTI_INTENT_* code.  */ /* short intent_code;    */   /* 504 */
   char intent_name[16]; /*!< 'name' or meaning of data. */ /* char intent_name[16]; */  /* 508 */
   char dim_info;        /*!< MRI slice ordering.   */      /* char dim_info;        */  /* 524 */
   char unused_str[15];  /*!< unused, filled with \0 */                                  /* 525 */
} ;                   /**** 540 bytes total ****/
```
ISMRMRD_Image:
```
typedef struct ISMRMRD_ImageHeader {
    uint16_t version;                                    /**< First unsigned int indicates the version */
    uint16_t data_type;                                  /**< e.g. unsigned short, float, complex float, etc. */
    uint64_t flags;                                      /**< bit field with flags */
    uint32_t measurement_uid;                            /**< Unique ID for the measurement  */
    uint16_t matrix_size[3];                             /**< Pixels in the 3 spatial dimensions */
    float field_of_view[3];                              /**< Size (in mm) of the 3 spatial dimensions */
    uint16_t channels;                                   /**< Number of receive channels */
    float position[3];                                   /**< Three-dimensional spatial offsets from isocenter */
    float read_dir[3];                                   /**< Directional cosines of the readout/frequency encoding */
    float phase_dir[3];                                  /**< Directional cosines of the phase */
    float slice_dir[3];                                  /**< Directional cosines of the slice direction */
    float patient_table_position[3];                     /**< Patient table off-center */
    uint16_t average;                                    /**< e.g. signal average number */
    uint16_t slice;                                      /**< e.g. imaging slice number */
    uint16_t contrast;                                   /**< e.g. echo number in multi-echo */
    uint16_t phase;                                      /**< e.g. cardiac phase number */
    uint16_t repetition;                                 /**< e.g. dynamic number for dynamic scanning */
    uint16_t set;                                        /**< e.g. flow encodning set */
    uint32_t acquisition_time_stamp;                     /**< Acquisition clock */
    uint32_t physiology_time_stamp[ISMRMRD_PHYS_STAMPS]; /**< Physiology time stamps, e.g. ecg, breathing, etc. */
    uint16_t image_type;                                 /**< e.g. magnitude, phase, complex, real, imag, etc. */
    uint16_t image_index;                                /**< e.g. image number in series of images  */
    uint16_t image_series_index;                         /**< e.g. series number */
    int32_t user_int[ISMRMRD_USER_INTS];                 /**< Free user parameters */
    float user_float[ISMRMRD_USER_FLOATS];               /**< Free user parameters */
    uint32_t attribute_string_len;                       /**< Length of attributes string */
} ISMRMRD_ImageHeader;
```

**Comment by hansenms** [comment]
@ghisvail thanks for your comments. I don't necessarily disagree with any of your points with the exception of the idea of embedding metadata in the file name, which really sounds unappealing. 

I think we can certainly revisit the idea of using nifti at some point but there was little appetite for it on the conference call on Friday. I think the best approach may be to have the Gadgetron (and other downstream tools) add the ability to save in nifti (and other formats) and keep the ISMRMRD image format for now.
